### ISSUE TITLE
While using package with docker desktop 

### ISSUE THREAD

**Issue by deepakkatara** [Brooooooklyn/snappy#122]
HI Team,

On macOS, I use the snappy package, which is successful. however, the moment I attempt to launch the project locally using Docker Desktop, an issue occurs while starting the container-

`Error: Cannot find module '@napi-rs/snappy-linux-x64-musl'
 Require stack:
 - /code/node_modules/snappy/index.js
 - /code/dist/server/index.js
 - /code/index.js
     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
     at Function.wrappedResolveFilename [as _resolveFilename] (/code/node_modules/newrelic/lib/shimmer.js:291:42)
     at Module._load (node:internal/modules/cjs/loader:920:27)
     at Function.wrappedLoad [as _load] (/code/node_modules/newrelic/lib/shimmer.js:307:24)
     at Module.require (node:internal/modules/cjs/loader:1141:19)
     at require (node:internal/modules/cjs/helpers:110:18)
     at Object.<anonymous> (/code/node_modules/snappy/index.js:1:2955)
     at Module._compile (node:internal/modules/cjs/loader:1254:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
     at Module.load (node:internal/modules/cjs/loader:1117:32) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/code/node_modules/snappy/index.js',
     '/code/dist/server/index.js',
     '/code/index.js'
   ]
 }`

The potential problem that I see is connected to optionalDependencies because it only installs @napi-rs/snappy-darwin-x64 compatible with Mac and searches for Linux @napi-rs dependencies when I run it in a docker container. 

**Docker info** 
<img width="999" alt="image" src="https://user-images.githubusercontent.com/26602033/232016315-d4e98d0a-46bf-4840-94c0-4c17e26c52cf.png">

What could be the potential solution  of this?

**Comment by Brooooooklyn** [comment]
@deepakkatara you are supposed to re-install your dependencies in your docker environment

**Comment by deepakkatara** [comment]
I am doing this already. sample docker file-

FROM node:18-alpine

# set working directory
WORKDIR /code

# Copy the package.json and yarn.lock files into the container at /app
COPY package.json yarn.lock ./

# Install dependencies using yarn
RUN yarn install --frozen-lockfile --production=false

# Copy the rest of the application files into the container at /app
COPY . .

# expose port and define CMD
EXPOSE 3000

CMD [ "npm", "run", "start" ]

**Comment by Brooooooklyn** [comment]
The `COPY . .` is after `yarn install`, so your installed node_modules in Docker is overridden by the host node_modules.

**Comment by eabrouwer3** [comment]
I'm getting the same issue, and I think it's because my local arch is different than the docker arch. So my `package-lock.json` file has this:
```json
    "node_modules/snappy/node_modules/@napi-rs/snappy-darwin-arm64": {
      "version": "7.2.2",
      "cpu": [
        "arm64"
      ],
      "license": "MIT",
      "optional": true,
      "os": [
        "darwin"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
```
while the Docker runtime (`node:18-alpine`) needs `@napi-rs/snappy-linux-arm64-musl`. But I only want to run `npm ci` in the docker container, not `npm i`. Maybe I could manually detect which one it needs and install that specific engine? Thoughts, @Brooooooklyn?

**Comment by Brooooooklyn** [comment]
@eabrouwer3 see https://github.com/npm/cli/issues/4828

You can remove `node_modules` and `package-lock.json` and re-generate the `package-lock.json`

**Comment by eabrouwer3** [comment]
I ended up adding all of the runtimes as optional dependencies, so that no matter where I'm running `npm ci` from, I get all of them.

```json
  "optionalDependencies": {
    "@napi-rs/snappy-android-arm-eabi": "~7.2.2",
    "@napi-rs/snappy-android-arm64": "~7.2.2",
    "@napi-rs/snappy-darwin-arm64": "~7.2.2",
    "@napi-rs/snappy-darwin-x64": "~7.2.2",
    "@napi-rs/snappy-freebsd-x64": "~7.2.2",
    "@napi-rs/snappy-linux-arm-gnueabihf": "~7.2.2",
    "@napi-rs/snappy-linux-arm64-gnu": "~7.2.2",
    "@napi-rs/snappy-linux-arm64-musl": "~7.2.2",
    "@napi-rs/snappy-linux-x64-gnu": "~7.2.2",
    "@napi-rs/snappy-linux-x64-musl": "~7.2.2",
    "@napi-rs/snappy-win32-arm64-msvc": "7.2.2",
    "@napi-rs/snappy-win32-ia32-msvc": "~7.2.2",
    "@napi-rs/snappy-win32-x64-msvc": "~7.2.2"
  }
```
